cnendict_internal = {
    "我":"I",
    "你":"you",
    "他":"he",
    "她":"she",
    "它":"it",
    "我们":"we",
    "你们":"you",
    "他们":"they",
    "她们":"they",
    "它们":"they",
    "小":"small",
    "大":"big",
    "猫":"cat",
    "狗":"dog",
    "马":"horse",
    "打":"beat",
    "喂":"feed",
    "溜":"walk",
    "养":"raise",
    "爱":"love",
    "吃":"eat",
    "喝":"drink",
    "画":"draw",
    "喜欢":"like",
    "饲养":"raise",
    "抚摸":"pet",
    "丢弃":"abandon",
    "寻找":"search",
    "呼唤":"call out",
    "轻吻":"kiss gently"
}
